### ISSUE TITLE
message for solved challenges are confusing

### ISSUE THREAD

**Issue by dtwalter** [mitre-cyber-academy/embedded-ctf-scoreboard#3]
When a flag is captured the current message says: 
"Solve challenge <Category> <Points>"

This is confusing because the current challenges are all in the same category and the point values are changing dynamically throughout the competition.  Would be better to have the specific challenge name listed in addition to the points.  The category is not really helpful unless we create new categories and re-assign.

**Comment by rbclark** [comment]
Since the score is changing all the time anyway, would you prefer the point value left off altogether? It would then just say `Solved challenge "Challenge B-1"`

**Comment by rbclark** [comment]
Closed in a584c3f6a651631739f66795d422883b328aec85
